language: scala

jdk:
- oraclejdk8

env:
- SCALA_2_12=2.12.3

scala:
- 2.11.11
- $SCALA_2_12


before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.sbt/cache
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.ivy2

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_80bb47bfd841_key -iv $encrypted_80bb47bfd841_iv -in secring.gpg.enc -out secring.gpg -d;
  fi

script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI;

- if [ "$TRAVIS_SCALA_VERSION" = "$SCALA_2_12" ]; then
    sbt ++$TRAVIS_SCALA_VERSION protogen/compile;
  fi

after_success:
- bash <(curl -s https://codecov.io/bash) -t 5b75b318-ab71-4fbc-9203-bfa7765cdbdc

- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess

- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_SCALA_VERSION" = "$SCALA_2_12" ]; then
    if grep -q "SNAPSHOT" version.sbt; then
      sbt ++$TRAVIS_SCALA_VERSION protogen/publish;
    else
      git reset --hard HEAD;
      git clean -f;
      git checkout master;
      git pull origin master;
      sbt ++$TRAVIS_SCALA_VERSION protogen/release;
    fi
  fi