language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.12
  - 2.12.8
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
  - "$HOME/.sbt/cache"
  - "$HOME/.sbt/1.0"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.ivy2"
before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_95edac5cb8ef_key -iv $encrypted_95edac5cb8ef_iv -in secring.gpg.enc -out secring.gpg -d; fi
install:
  - rvm use 2.3.0 --install --fuzzy
  - gem install sass
  - gem install jekyll -v 3.2.1
script:
  - if [ $TRAVIS_SCALA_VERSION = "2.12.8" ]; then sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate docs/tut; fi
  - if [ $TRAVIS_SCALA_VERSION = "2.11.12" ]; then sbt ++$TRAVIS_SCALA_VERSION clean test; fi
  - bash <(curl -s https://codecov.io/bash)
stages:
- test
- plugin
- deployPlugin
- deploy
- microsite
jobs:
  include:
    - stage: plugin
      scala: 2.12.8
      script:
        - sbt ++$TRAVIS_SCALA_VERSION idlgen-core/test
        - sbt ++$TRAVIS_SCALA_VERSION idlgen-sbt/test
        - sbt ++$TRAVIS_SCALA_VERSION publishLocal idlgen-sbt/publishLocal idlgen-sbt/scripted
    - stage: deployPlugin
      scala: 2.12.8
      if: branch = master AND type != pull_request AND env(SKIP_SBT_DEPLOY) = false
      script:
        - if grep -q "SNAPSHOT" version.sbt; then
            sbt idlgen-sbt/publish;
          else
            sbt idlgen-sbt/release;
          fi
    - stage: deploy
      scala: 2.12.8
      if: branch = master AND type != pull_request
      script:
        - if grep -q "SNAPSHOT" version.sbt; then
            sbt +publish;
            sbt idlgen-sbt/publish;
          else
            sbt orgUpdateDocFiles;
            git reset --hard HEAD;
            git clean -f;
            git checkout master;
            git pull origin master;
            sbt release;
          fi
    - stage: microsite
      scala: 2.12.8
      if: branch = master AND type != pull_request
      script:
        - if grep -q "SNAPSHOT" version.sbt; then
            echo "Skipping microsite publication, snapshot version";
          else
            sbt docs/publishMicrosite;
          fi
